# Generated by Django 5.0.6 on 2025-02-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_signupmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pimage', models.ImageField(null=True, upload_to='photos')),
                ('pprice', models.FloatField()),
                ('desc', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.signupmodel')),
            ],
        ),
    ]
