# Generated by Django 5.0.6 on 2025-03-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalamount', models.FloatField()),
                ('orderstatus', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.signupmodel')),
            ],
        ),
    ]
