# Generated by Django 5.0.6 on 2025-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
