# Generated by Django 5.0.6 on 2025-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcolor',
            field=models.TextField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
