# Generated by Django 5.0.6 on 2025-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_pcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prentprice',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
