# Generated by Django 5.1.4 on 2025-04-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_pcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentalmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('total_rent', models.FloatField()),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.signupmodel')),
            ],
        ),
    ]
