# Generated by Django 5.0.6 on 2025-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalmodel',
            name='booking_date',
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='payment_status',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
