# Generated by Django 5.0.6 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_rentalmodel_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmodel',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
