# Generated by Django 5.0.6 on 2025-04-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_rentalmodel_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rental',
        ),
    ]
