# Generated by Django 5.0.6 on 2025-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
